### ISSUE TITLE
Loggo cannot handle lambda or functools.partial class attributes

### ISSUE THREAD

**Issue by interrogator** [bitpanda-labs/loggo#86] opened 2019-06-05 18:47 UTC
Right now we are missing a coverage line for callables without `__name__`, because these are very rare. `functools.partial` objects don't have `__name__` but are callable, so I decided to try to write a test, but it threw an unexpected error, which we probably should handle:

```python
from loggo import Loggo
from functools import partial
loggo = Loggo(do_print=True)

@loggo 
class WithUnnamed: 
    basetwo = partial(int, base=2) 

WithUnnamed().basetwo()                                                 
ValueError                                Traceback (most recent call last)
<ipython-input-36-8625eace0720> in <module>
----> 1 WithUnnamed().basetwo()

~/work/loggo/loggo/loggo.py in full_decoration(*args, **kwargs)
    242             Args and kwargs are for/from the decorated function
    243             """
--> 244             bound = self._params_to_dict(function, *args, **kwargs)
    245             # bound will be none if inspect signature binding failed. in this
    246             # case, error log was created, raised if self.raise_logging_errors

~/work/loggo/loggo/loggo.py in _params_to_dict(self, function, *args, **kwargs)
    331         Turn args and kwargs into an OrderedDict of {param_name: value}
    332         """
--> 333         sig = inspect.signature(function)
    334         bound = sig.bind(*args, **kwargs).arguments
    335         if bound:

/usr/lib/python3.6/inspect.py in signature(obj, follow_wrapped)
   3055 def signature(obj, *, follow_wrapped=True):
   3056     """Get a signature object for the passed callable."""
-> 3057     return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
   3058 
   3059 

/usr/lib/python3.6/inspect.py in from_callable(cls, obj, follow_wrapped)
   2805         """Constructs Signature for the given callable object."""
   2806         return _signature_from_callable(obj, sigcls=cls,
-> 2807                                         follow_wrapper_chains=follow_wrapped)
   2808 
   2809     @property

/usr/lib/python3.6/inspect.py in _signature_from_callable(obj, follow_wrapper_chains, skip_bound_arg, sigcls)
   2276             follow_wrapper_chains=follow_wrapper_chains,
   2277             skip_bound_arg=skip_bound_arg,
-> 2278             sigcls=sigcls)
   2279         return _signature_get_partial(wrapped_sig, obj)
   2280 

/usr/lib/python3.6/inspect.py in _signature_from_callable(obj, follow_wrapper_chains, skip_bound_arg, sigcls)
   2345                 else:
   2346                     raise ValueError(
-> 2347                         'no signature found for builtin type {!r}'.format(obj))
   2348 
   2349     elif not isinstance(obj, _NonUserDefinedCallables):

ValueError: no signature found for builtin type <class 'int'>
```

@gcarq @hukkinj1 you guys ever used `partial`? How should loggo handle it?

**Comment by interrogator** [comment] 2019-06-05 19:01
A few extra things. First, we can easily identify partials:

```python
In [1]: from functools import partial                                                                                                                                             

In [2]: basetwo = partial(int, 2)                                                                                                                                                 

In [3]: basetwo                                                                                                                                                                   
Out[3]: functools.partial(<class 'int'>, 2)

In [4]: isinstance(basetwo, partial)                                                                                                                                              
Out[4]: True
```

Second, on a related note, I can also get an error with:

```python
In [9]: @loggo 
   ...: class X: 
   ...:     y = lambda x: len(x) 

In [13]: X().y('this')                                                                                                                                                            
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-21d3bd2ab276> in <module>
----> 1 X().y('this')

~/work/loggo/loggo/loggo.py in full_decoration(*args, **kwargs)
    242             Args and kwargs are for/from the decorated function
    243             """
--> 244             bound = self._params_to_dict(function, *args, **kwargs)
    245             # bound will be none if inspect signature binding failed. in this
    246             # case, error log was created, raised if self.raise_logging_errors

~/work/loggo/loggo/loggo.py in _params_to_dict(self, function, *args, **kwargs)
    332         """
    333         sig = inspect.signature(function)
--> 334         bound = sig.bind(*args, **kwargs).arguments
    335         if bound:
    336             first = list(bound)[0]

/usr/lib/python3.6/inspect.py in bind(*args, **kwargs)
   2987         if the passed arguments can not be bound.
   2988         """
-> 2989         return args[0]._bind(args[1:], kwargs)
   2990 
   2991     def bind_partial(*args, **kwargs):

/usr/lib/python3.6/inspect.py in _bind(self, args, kwargs, partial)
   2908                     param = next(parameters)
   2909                 except StopIteration:
-> 2910                     raise TypeError('too many positional arguments') from None
   2911                 else:
   2912                     if param.kind in (_VAR_KEYWORD, _KEYWORD_ONLY):

TypeError: too many positional arguments
```

lambda is fairly common in some kinds of code, so i suggest we deal with these soonish

**Comment by hukkinj1** [comment] 2019-06-05 19:11
This seems like a dupe of an issue we already closed (https://github.com/bitpanda-labs/loggo/issues/15) and fixed (https://github.com/bitpanda-labs/loggo/commit/ac83535c8d9cc915132024085c616f80e15b67cc).

IMO we just set some value for the signature that tells us that the decoration/auto-logging of this callable failed because we cant get the signature, and get on with it.

**Comment by interrogator** [comment] 2019-06-05 20:55
The fix there was a kind of catchall for unexpected cases, whereas here we're dealing with known types that loggo may struggle with. I really prefer the idea of correctly handling each new failing case as we find them, as there really aren't that many kinds of callable.

for partial and lambda, it seems like we can/should just handle them as unique cases. We have the class and attribute name, so we can still reconstruct call signatures. Why fail and not log when we could succeed and log?

**Comment by hukkinj1** [comment] 2019-06-05 21:32
Well my take on it is to solve it with the simplest way possible. Two cases, failure or no failure, seems like the simplest way to look at it. Nobody has ever missed logs for these partial or lambda functions so far, so why implement them, maintain the code, test the code, etc, unless we have proof that someone needs this functionality.

Ofc if someone comes up with nice code to handle these as special cases, with good test coverage etc. I'll still merge, but dont see myself ever implementing that.

**Comment by interrogator** [comment] 2019-06-17 09:55
Yeah, I agree. I never use partial, and assigning lambdas to variables is bad practice anyway, since why not just make a function at that point. Would prefer to leave this issue up, and yeah, if anybody wants to code the fixes, they are welcome.

**Closed** 2019-07-17 10:56 UTC
